import { MEDIA_AUDIO_FIELD_LABELS } from "./media-audio-field-metadata.js";
import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  meta: "元数据",
  "meta.lastTouchedVersion": "配置最后修改版本",
  "meta.lastTouchedAt": "配置最后修改时间",
  env: "环境",
  "env.shellEnv": "Shell 环境导入",
  "env.shellEnv.enabled": "Shell 环境导入已启用",
  "env.shellEnv.timeoutMs": "Shell 环境导入超时(毫秒)",
  "env.vars": "环境变量覆盖",
  wizard: "向导状态",
  "wizard.lastRunAt": "向导最后运行时间",
  "wizard.lastRunVersion": "向导最后运行版本",
  "wizard.lastRunCommit": "向导最后运行提交",
  "wizard.lastRunCommand": "向导最后运行命令",
  "wizard.lastRunMode": "向导最后运行模式",
  diagnostics: "诊断",
  "diagnostics.otel": "OpenTelemetry",
  "diagnostics.cacheTrace": "缓存跟踪",
  logging: "日志",
  "logging.level": "日志级别",
  "logging.file": "日志文件路径",
  "logging.consoleLevel": "控制台日志级别",
  "logging.consoleStyle": "控制台日志样式",
  "logging.redactSensitive": "敏感数据编辑模式",
  "logging.redactPatterns": "自定义编辑模式",
  cli: "CLI",
  "cli.banner": "CLI Banner",
  "cli.banner.taglineMode": "CLI Banner Tagline Mode",
  update: "Updates",
  "update.channel": "Update Channel",
  "update.checkOnStart": "Update Check on Start",
  "update.auto.enabled": "Auto Update Enabled",
  "update.auto.stableDelayHours": "Auto Update Stable Delay (hours)",
  "update.auto.stableJitterHours": "Auto Update Stable Jitter (hours)",
  "update.auto.betaCheckIntervalHours": "Auto Update Beta Check Interval (hours)",
  "diagnostics.enabled": "Diagnostics Enabled",
  "diagnostics.flags": "Diagnostics Flags",
  "diagnostics.stuckSessionWarnMs": "Stuck Session Warning Threshold (ms)",
  "diagnostics.otel.enabled": "OpenTelemetry Enabled",
  "diagnostics.otel.endpoint": "OpenTelemetry Endpoint",
  "diagnostics.otel.protocol": "OpenTelemetry Protocol",
  "diagnostics.otel.headers": "OpenTelemetry Headers",
  "diagnostics.otel.serviceName": "OpenTelemetry Service Name",
  "diagnostics.otel.traces": "OpenTelemetry Traces Enabled",
  "diagnostics.otel.metrics": "OpenTelemetry Metrics Enabled",
  "diagnostics.otel.logs": "OpenTelemetry Logs Enabled",
  "diagnostics.otel.sampleRate": "OpenTelemetry Trace Sample Rate",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry Flush Interval (ms)",
  "diagnostics.cacheTrace.enabled": "Cache Trace Enabled",
  "diagnostics.cacheTrace.filePath": "Cache Trace File Path",
  "diagnostics.cacheTrace.includeMessages": "Cache Trace Include Messages",
  "diagnostics.cacheTrace.includePrompt": "Cache Trace Include Prompt",
  "diagnostics.cacheTrace.includeSystem": "Cache Trace Include System",
  "agents.list.*.identity.avatar": "Identity Avatar",
  "agents.list.*.skills": "Agent Skill Filter",
  "agents.list[].runtime": "Agent Runtime",
  "agents.list[].runtime.type": "Agent Runtime Type",
  "agents.list[].runtime.acp": "Agent ACP Runtime",
  "agents.list[].runtime.acp.agent": "Agent ACP Harness Agent",
  "agents.list[].runtime.acp.backend": "Agent ACP Backend",
  "agents.list[].runtime.acp.mode": "Agent ACP Mode",
  "agents.list[].runtime.acp.cwd": "Agent ACP Working Directory",
  "agents.list[].thinkingDefault": "Agent Thinking Default",
  "agents.list[].reasoningDefault": "Agent Reasoning Default",
  "agents.list[].fastModeDefault": "Agent Fast Mode Default",
  agents: "Agents",
  "agents.defaults": "Agent Defaults",
  "agents.list": "Agent List",
  gateway: "Gateway",
  "gateway.port": "Gateway Port",
  "gateway.mode": "Gateway Mode",
  "gateway.bind": "Gateway Bind Mode",
  "gateway.customBindHost": "Gateway Custom Bind Host",
  "gateway.controlUi": "Control UI",
  "gateway.controlUi.enabled": "Control UI Enabled",
  "gateway.auth": "Gateway Auth",
  "gateway.auth.mode": "Gateway Auth Mode",
  "gateway.auth.allowTailscale": "Gateway Auth Allow Tailscale Identity",
  "gateway.auth.rateLimit": "Gateway Auth Rate Limit",
  "gateway.auth.trustedProxy": "Gateway Trusted Proxy Auth",
  "gateway.trustedProxies": "Gateway Trusted Proxy CIDRs",
  "gateway.allowRealIpFallback": "Gateway Allow x-real-ip Fallback",
  "gateway.tools": "Gateway Tool Exposure Policy",
  "gateway.tools.allow": "Gateway Tool Allowlist",
  "gateway.tools.deny": "Gateway Tool Denylist",
  "gateway.channelHealthCheckMinutes": "Gateway Channel Health Check Interval (min)",
  "gateway.channelStaleEventThresholdMinutes": "Gateway Channel Stale Event Threshold (min)",
  "gateway.channelMaxRestartsPerHour": "Gateway Channel Max Restarts Per Hour",
  "gateway.tailscale": "Gateway Tailscale",
  "gateway.tailscale.mode": "Gateway Tailscale Mode",
  "gateway.tailscale.resetOnExit": "Gateway Tailscale Reset on Exit",
  "gateway.remote": "Remote Gateway",
  "gateway.remote.transport": "Remote Gateway Transport",
  "gateway.reload": "Config Reload",
  "gateway.tls": "Gateway TLS",
  "gateway.tls.enabled": "Gateway TLS Enabled",
  "gateway.tls.autoGenerate": "Gateway TLS Auto-Generate Cert",
  "gateway.tls.certPath": "Gateway TLS Certificate Path",
  "gateway.tls.keyPath": "Gateway TLS Key Path",
  "gateway.tls.caPath": "Gateway TLS CA Path",
  "gateway.http": "Gateway HTTP API",
  "gateway.http.endpoints": "Gateway HTTP Endpoints",
  "gateway.http.securityHeaders": "Gateway HTTP Security Headers",
  "gateway.http.securityHeaders.strictTransportSecurity": "Strict Transport Security Header",
  "gateway.remote.url": "Remote Gateway URL",
  "gateway.remote.sshTarget": "Remote Gateway SSH Target",
  "gateway.remote.sshIdentity": "Remote Gateway SSH Identity",
  "gateway.remote.token": "Remote Gateway Token",
  "gateway.remote.password": "Remote Gateway Password",
  "gateway.remote.tlsFingerprint": "Remote Gateway TLS Fingerprint",
  "gateway.auth.token": "Gateway Token",
  "gateway.auth.password": "Gateway Password",
  browser: "Browser",
  "browser.enabled": "Browser Enabled",
  "browser.cdpUrl": "Browser CDP URL",
  "browser.color": "Browser Accent Color",
  "browser.executablePath": "Browser Executable Path",
  "browser.headless": "Browser Headless Mode",
  "browser.noSandbox": "Browser No-Sandbox Mode",
  "browser.attachOnly": "Browser Attach-only Mode",
  "browser.cdpPortRangeStart": "Browser CDP Port Range Start",
  "browser.defaultProfile": "Browser Default Profile",
  "browser.profiles": "Browser Profiles",
  "browser.profiles.*.cdpPort": "Browser Profile CDP Port",
  "browser.profiles.*.cdpUrl": "Browser Profile CDP URL",
  "browser.profiles.*.userDataDir": "Browser Profile User Data Dir",
  "browser.profiles.*.driver": "Browser Profile Driver",
  "browser.profiles.*.attachOnly": "Browser Profile Attach-only Mode",
  "browser.profiles.*.color": "Browser Profile Accent Color",
  tools: "Tools",
  "tools.allow": "Tool Allowlist",
  "tools.deny": "Tool Denylist",
  "tools.web": "Web Tools",
  "tools.exec": "Exec Tool",
  "tools.media.image.enabled": "Enable Image Understanding",
  "tools.media.image.maxBytes": "Image Understanding Max Bytes",
  "tools.media.image.maxChars": "Image Understanding Max Chars",
  "tools.media.image.prompt": "Image Understanding Prompt",
  "tools.media.image.timeoutSeconds": "Image Understanding Timeout (sec)",
  "tools.media.image.attachments": "Image Understanding Attachment Policy",
  "tools.media.image.models": "Image Understanding Models",
  "tools.media.image.scope": "Image Understanding Scope",
  "tools.media.models": "Media Understanding Shared Models",
  "tools.media.concurrency": "Media Understanding Concurrency",
  ...MEDIA_AUDIO_FIELD_LABELS,
  "tools.media.video.enabled": "Enable Video Understanding",
  "tools.media.video.maxBytes": "Video Understanding Max Bytes",
  "tools.media.video.maxChars": "Video Understanding Max Chars",
  "tools.media.video.prompt": "Video Understanding Prompt",
  "tools.media.video.timeoutSeconds": "Video Understanding Timeout (sec)",
  "tools.media.video.attachments": "Video Understanding Attachment Policy",
  "tools.media.video.models": "Video Understanding Models",
  "tools.media.video.scope": "Video Understanding Scope",
  "tools.links.enabled": "Enable Link Understanding",
  "tools.links.maxLinks": "Link Understanding Max Links",
  "tools.links.timeoutSeconds": "Link Understanding Timeout (sec)",
  "tools.links.models": "Link Understanding Models",
  "tools.links.scope": "Link Understanding Scope",
  "tools.profile": "Tool Profile",
  "tools.alsoAllow": "Tool Allowlist Additions",
  "agents.list[].tools.profile": "Agent Tool Profile",
  "agents.list[].tools.alsoAllow": "Agent Tool Allowlist Additions",
  "tools.byProvider": "Tool Policy by Provider",
  "agents.list[].tools.byProvider": "Agent Tool Policy by Provider",
  "tools.exec.applyPatch.enabled": "Enable apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch Workspace-Only",
  "tools.exec.applyPatch.allowModels": "apply_patch Model Allowlist",
  "tools.loopDetection.enabled": "Tool-loop Detection",
  "tools.loopDetection.historySize": "Tool-loop History Size",
  "tools.loopDetection.warningThreshold": "Tool-loop Warning Threshold",
  "tools.loopDetection.criticalThreshold": "Tool-loop Critical Threshold",
  "tools.loopDetection.globalCircuitBreakerThreshold": "Tool-loop Global Circuit Breaker Threshold",
  "tools.loopDetection.detectors.genericRepeat": "Tool-loop Generic Repeat Detection",
  "tools.loopDetection.detectors.knownPollNoProgress": "Tool-loop Poll No-Progress Detection",
  "tools.loopDetection.detectors.pingPong": "Tool-loop Ping-Pong Detection",
  "tools.fs.workspaceOnly": "Workspace-only FS tools",
  "tools.sessions.visibility": "Session Tools Visibility",
  "tools.exec.notifyOnExit": "Exec Notify On Exit",
  "tools.exec.notifyOnExitEmptySuccess": "Exec Notify On Empty Success",
  "tools.exec.approvalRunningNoticeMs": "Exec Approval Running Notice (ms)",
  "tools.exec.host": "Exec Host",
  "tools.exec.security": "Exec Security",
  "tools.exec.ask": "Exec Ask",
  "tools.exec.node": "Exec Node Binding",
  "tools.agentToAgent": "Agent-to-Agent Tool Access",
  "tools.agentToAgent.enabled": "Enable Agent-to-Agent Tool",
  "tools.agentToAgent.allow": "Agent-to-Agent Target Allowlist",
  "tools.elevated": "Elevated Tool Access",
  "tools.elevated.enabled": "Enable Elevated Tool Access",
  "tools.elevated.allowFrom": "Elevated Tool Allow Rules",
  "tools.subagents": "Subagent Tool Policy",
  "tools.subagents.tools": "Subagent Tool Allow/Deny Policy",
  "tools.sandbox": "Sandbox Tool Policy",
  "tools.sandbox.tools": "Sandbox Tool Allow/Deny Policy",
  "tools.exec.pathPrepend": "Exec PATH Prepend",
  "tools.exec.safeBins": "Exec Safe Bins",
  "tools.exec.strictInlineEval": "Require Inline-Eval Approval",
  "tools.exec.safeBinTrustedDirs": "Exec Safe Bin Trusted Dirs",
  "tools.exec.safeBinProfiles": "Exec Safe Bin Profiles",
  approvals: "Approvals",
  "approvals.exec": "Exec Approval Forwarding",
  "approvals.exec.enabled": "Forward Exec Approvals",
  "approvals.exec.mode": "Approval Forwarding Mode",
  "approvals.exec.agentFilter": "Approval Agent Filter",
  "approvals.exec.sessionFilter": "Approval Session Filter",
  "approvals.exec.targets": "Approval Forwarding Targets",
  "approvals.exec.targets[].channel": "Approval Target Channel",
  "approvals.exec.targets[].to": "Approval Target Destination",
  "approvals.exec.targets[].accountId": "Approval Target Account ID",
  "approvals.exec.targets[].threadId": "Approval Target Thread ID",
  "tools.message.allowCrossContextSend": "Allow Cross-Context Messaging",
  "tools.message.crossContext.allowWithinProvider": "Allow Cross-Context (Same Provider)",
  "tools.message.crossContext.allowAcrossProviders": "Allow Cross-Context (Across Providers)",
  "tools.message.crossContext.marker.enabled": "Cross-Context Marker",
  "tools.message.crossContext.marker.prefix": "Cross-Context Marker Prefix",
  "tools.message.crossContext.marker.suffix": "Cross-Context Marker Suffix",
  "tools.message.broadcast.enabled": "Enable Message Broadcast",
  "tools.web.search.enabled": "Enable Web Search Tool",
  "tools.web.search.provider": "Web Search Provider",
  "tools.web.search.maxResults": "Web Search Max Results",
  "tools.web.search.timeoutSeconds": "Web Search Timeout (sec)",
  "tools.web.search.cacheTtlMinutes": "Web Search Cache TTL (min)",
  "tools.web.fetch.enabled": "Enable Web Fetch Tool",
  "tools.web.fetch.maxChars": "Web Fetch Max Chars",
  "tools.web.fetch.maxCharsCap": "Web Fetch Hard Max Chars",
  "tools.web.fetch.timeoutSeconds": "Web Fetch Timeout (sec)",
  "tools.web.fetch.cacheTtlMinutes": "Web Fetch Cache TTL (min)",
  "tools.web.fetch.maxRedirects": "Web Fetch Max Redirects",
  "tools.web.fetch.userAgent": "Web Fetch User-Agent",
  "tools.web.fetch.readability": "Web Fetch Readability Extraction",
  "tools.web.fetch.firecrawl.enabled": "Enable Firecrawl Fallback",
  "tools.web.fetch.firecrawl.apiKey": "Firecrawl API Key", // pragma: allowlist secret
  "tools.web.fetch.firecrawl.baseUrl": "Firecrawl Base URL",
  "tools.web.fetch.firecrawl.onlyMainContent": "Firecrawl Main Content Only",
  "tools.web.fetch.firecrawl.maxAgeMs": "Firecrawl Cache Max Age (ms)",
  "tools.web.fetch.firecrawl.timeoutSeconds": "Firecrawl Timeout (sec)",
  "gateway.controlUi.basePath": "Control UI Base Path",
  "gateway.controlUi.root": "Control UI Assets Root",
  "gateway.controlUi.allowedOrigins": "Control UI Allowed Origins",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback":
    "Dangerously Allow Host-Header Origin Fallback",
  "gateway.controlUi.allowInsecureAuth": "Insecure Control UI Auth Toggle",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "Dangerously Disable Control UI Device Auth",
  "gateway.push": "Gateway Push Delivery",
  "gateway.push.apns": "Gateway APNs Delivery",
  "gateway.push.apns.relay": "Gateway APNs Relay",
  "gateway.push.apns.relay.baseUrl": "Gateway APNs Relay Base URL",
  "gateway.push.apns.relay.timeoutMs": "Gateway APNs Relay Timeout (ms)",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI Chat Completions Endpoint",
  "gateway.http.endpoints.chatCompletions.maxBodyBytes": "OpenAI Chat Completions Max Body Bytes",
  "gateway.http.endpoints.chatCompletions.maxImageParts": "OpenAI Chat Completions Max Image Parts",
  "gateway.http.endpoints.chatCompletions.maxTotalImageBytes":
    "OpenAI Chat Completions Max Total Image Bytes",
  "gateway.http.endpoints.chatCompletions.images": "OpenAI Chat Completions Image Limits",
  "gateway.http.endpoints.chatCompletions.images.allowUrl":
    "OpenAI Chat Completions Allow Image URLs",
  "gateway.http.endpoints.chatCompletions.images.urlAllowlist":
    "OpenAI Chat Completions Image URL Allowlist",
  "gateway.http.endpoints.chatCompletions.images.allowedMimes":
    "OpenAI Chat Completions Image MIME Allowlist",
  "gateway.http.endpoints.chatCompletions.images.maxBytes":
    "OpenAI Chat Completions Image Max Bytes",
  "gateway.http.endpoints.chatCompletions.images.maxRedirects":
    "OpenAI Chat Completions Image Max Redirects",
  "gateway.http.endpoints.chatCompletions.images.timeoutMs":
    "OpenAI Chat Completions Image Timeout (ms)",
  "gateway.reload.mode": "Config Reload Mode",
  "gateway.reload.debounceMs": "Config Reload Debounce (ms)",
  "gateway.reload.deferralTimeoutMs": "Restart Deferral Timeout (ms)",
  "gateway.nodes.browser.mode": "Gateway Node Browser Mode",
  "gateway.nodes.browser.node": "Gateway Node Browser Pin",
  "gateway.nodes.allowCommands": "Gateway Node Allowlist (Extra Commands)",
  "gateway.nodes.denyCommands": "Gateway Node Denylist",
  nodeHost: "Node Host",
  "nodeHost.browserProxy": "Node Browser Proxy",
  "nodeHost.browserProxy.enabled": "Node Browser Proxy Enabled",
  "nodeHost.browserProxy.allowProfiles": "Node Browser Proxy Allowed Profiles",
  media: "Media",
  "media.preserveFilenames": "Preserve Media Filenames",
  "media.ttlHours": "Media Retention TTL (hours)",
  audio: "Audio",
  "audio.transcription": "Audio Transcription",
  "audio.transcription.command": "Audio Transcription Command",
  "audio.transcription.timeoutSeconds": "Audio Transcription Timeout (sec)",
  bindings: "Bindings",
  "bindings[].type": "Binding Type",
  "bindings[].agentId": "Binding Agent ID",
  "bindings[].match": "Binding Match Rule",
  "bindings[].match.channel": "Binding Channel",
  "bindings[].match.accountId": "Binding Account ID",
  "bindings[].match.peer": "Binding Peer Match",
  "bindings[].match.peer.kind": "Binding Peer Kind",
  "bindings[].match.peer.id": "Binding Peer ID",
  "bindings[].match.guildId": "Binding Guild ID",
  "bindings[].match.teamId": "Binding Team ID",
  "bindings[].match.roles": "Binding Roles",
  "bindings[].acp": "ACP Binding Overrides",
  "bindings[].acp.mode": "ACP Binding Mode",
  "bindings[].acp.label": "ACP Binding Label",
  "bindings[].acp.cwd": "ACP Binding Working Directory",
  "bindings[].acp.backend": "ACP Binding Backend",
  broadcast: "Broadcast",
  "broadcast.strategy": "Broadcast Strategy",
  "broadcast.*": "Broadcast Destination List",
  "skills.load.watch": "Watch Skills",
  "skills.load.watchDebounceMs": "Skills Watch Debounce (ms)",
  "agents.defaults.workspace": "Workspace",
  "agents.defaults.repoRoot": "Repo Root",
  "agents.defaults.bootstrapMaxChars": "Bootstrap Max Chars",
  "agents.defaults.bootstrapTotalMaxChars": "Bootstrap Total Max Chars",
  "agents.defaults.bootstrapPromptTruncationWarning": "Bootstrap Prompt Truncation Warning",
  "agents.defaults.envelopeTimezone": "Envelope Timezone",
  "agents.defaults.envelopeTimestamp": "Envelope Timestamp",
  "agents.defaults.envelopeElapsed": "Envelope Elapsed",
  "agents.defaults.memorySearch": "Memory Search",
  "agents.defaults.memorySearch.enabled": "Enable Memory Search",
  "agents.defaults.memorySearch.sources": "Memory Search Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra Memory Paths",
  "agents.defaults.memorySearch.multimodal": "Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.enabled": "Enable Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.modalities": "Memory Search Multimodal Modalities",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "Memory Search Multimodal Max File Bytes",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "Memory Search Session Index (Experimental)",
  "agents.defaults.memorySearch.provider": "Memory Search Provider",
  "agents.defaults.memorySearch.remote.baseUrl": "Remote Embedding Base URL",
  "agents.defaults.memorySearch.remote.apiKey": "Remote Embedding API Key",
  "agents.defaults.memorySearch.remote.headers": "Remote Embedding Headers",
  "agents.defaults.memorySearch.remote.batch.enabled": "Remote Batch Embedding Enabled",
  "agents.defaults.memorySearch.remote.batch.wait": "Remote Batch Wait for Completion",
  "agents.defaults.memorySearch.remote.batch.concurrency": "Remote Batch Concurrency",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "Remote Batch Poll Interval (ms)",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "Remote Batch Timeout (min)",
  "agents.defaults.memorySearch.model": "Memory Search Model",
  "agents.defaults.memorySearch.outputDimensionality": "Memory Search Output Dimensionality",
  "agents.defaults.memorySearch.fallback": "Memory Search Fallback",
  "agents.defaults.memorySearch.local.modelPath": "Local Embedding Model Path",
  "agents.defaults.memorySearch.store.path": "Memory Search Index Path",
  "agents.defaults.memorySearch.store.vector.enabled": "Memory Search Vector Index",
  "agents.defaults.memorySearch.store.vector.extensionPath": "Memory Search Vector Extension Path",
  "agents.defaults.memorySearch.chunking.tokens": "Memory Chunk Tokens",
  "agents.defaults.memorySearch.chunking.overlap": "Memory Chunk Overlap Tokens",
  "agents.defaults.memorySearch.sync.onSessionStart": "Index on Session Start",
  "agents.defaults.memorySearch.sync.onSearch": "Index on Search (Lazy)",
  "agents.defaults.memorySearch.sync.watch": "Watch Memory Files",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "Memory Watch Debounce (ms)",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "Session Delta Bytes",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "Session Delta Messages",
  "agents.defaults.memorySearch.sync.sessions.postCompactionForce":
    "Force Reindex After Compaction",
  "agents.defaults.memorySearch.query.maxResults": "Memory Search Max Results",
  "agents.defaults.memorySearch.query.minScore": "Memory Search Min Score",
  "agents.defaults.memorySearch.query.hybrid.enabled": "Memory Search Hybrid",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "Memory Search Vector Weight",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "Memory Search Text Weight",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "Memory Search Hybrid Candidate Multiplier",
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "Memory Search MMR Re-ranking",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "Memory Search MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "Memory Search Temporal Decay",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "内存搜索时间衰减半生命(天)",
  "agents.defaults.memorySearch.cache.enabled": "内存搜索嵌入缓存",
  "agents.defaults.memorySearch.cache.maxEntries": "内存搜索嵌入缓存最大条目数",
  memory: "内存",
  "memory.backend": "内存后端",
  "memory.citations": "内存引用模式",
  "memory.qmd.command": "QMD 二进制文件",
  "memory.qmd.mcporter": "QMD MCPorter",
  "memory.qmd.mcporter.enabled": "QMD MCPorter 已启用",
  "memory.qmd.mcporter.serverName": "QMD MCPorter 服务器名称",
  "memory.qmd.mcporter.startDaemon": "QMD MCPorter 启动守护程序",
  "memory.qmd.searchMode": "QMD 搜索模式",
  "memory.qmd.includeDefaultMemory": "QMD 包含默认内存",
  "memory.qmd.paths": "QMD 额外路径",
  "memory.qmd.paths.path": "QMD 路径",
  "memory.qmd.paths.pattern": "QMD 路径模式",
  "memory.qmd.paths.name": "QMD 路径名称",
  "memory.qmd.sessions.enabled": "QMD 会话索引",
  "memory.qmd.sessions.exportDir": "QMD 会话导出目录",
  "memory.qmd.sessions.retentionDays": "QMD 会话保留(天)",
  "memory.qmd.update.interval": "QMD 更新间隔",
  "memory.qmd.update.debounceMs": "QMD 更新防抖(毫秒)",
  "memory.qmd.update.onBoot": "QMD 启动时更新",
  "memory.qmd.update.waitForBootSync": "QMD 等待启动同步",
  "memory.qmd.update.embedInterval": "QMD 嵌入间隔",
  "memory.qmd.update.commandTimeoutMs": "QMD 命令超时(毫秒)",
  "memory.qmd.update.updateTimeoutMs": "QMD 更新超时(毫秒)",
  "memory.qmd.update.embedTimeoutMs": "QMD 嵌入超时(毫秒)",
  "memory.qmd.limits.maxResults": "QMD 最大结果数",
  "memory.qmd.limits.maxSnippetChars": "QMD 最大片段字符数",
  "memory.qmd.limits.maxInjectedChars": "QMD 最大注入字符数",
  "memory.qmd.limits.timeoutMs": "QMD 搜索超时(毫秒)",
  "memory.qmd.scope": "QMD 表面范围",
  auth: "认证",
  "auth.profiles": "认证配置文件",
  "auth.order": "认证配置文件顺序",
  "auth.cooldowns": "认证冷却时间",
  acp: "ACP",
  "acp.enabled": "ACP Enabled",
  "acp.dispatch.enabled": "ACP Dispatch Enabled",
  "acp.backend": "ACP Backend",
  "acp.defaultAgent": "ACP Default Agent",
  "acp.allowedAgents": "ACP Allowed Agents",
  "acp.maxConcurrentSessions": "ACP Max Concurrent Sessions",
  "acp.stream": "ACP Stream",
  "acp.stream.coalesceIdleMs": "ACP Stream Coalesce Idle (ms)",
  "acp.stream.maxChunkChars": "ACP Stream Max Chunk Chars",
  "acp.stream.repeatSuppression": "ACP Stream Repeat Suppression",
  "acp.stream.deliveryMode": "ACP Stream Delivery Mode",
  "acp.stream.hiddenBoundarySeparator": "ACP Stream Hidden Boundary Separator",
  "acp.stream.maxOutputChars": "ACP Stream Max Output Chars",
  "acp.stream.maxSessionUpdateChars": "ACP Stream Max Session Update Chars",
  "acp.stream.tagVisibility": "ACP Stream Tag Visibility",
  "acp.runtime.ttlMinutes": "ACP Runtime TTL (minutes)",
  "acp.runtime.installCommand": "ACP Runtime Install Command",
  models: "Models",
  "models.mode": "Model Catalog Mode",
  "models.providers": "Model Providers",
  "models.providers.*.baseUrl": "Model Provider Base URL",
  "models.providers.*.apiKey": "Model Provider API Key", // pragma: allowlist secret
  "models.providers.*.auth": "Model Provider Auth Mode",
  "models.providers.*.api": "Model Provider API Adapter",
  "models.providers.*.injectNumCtxForOpenAICompat": "Model Provider Inject num_ctx (OpenAI Compat)",
  "models.providers.*.headers": "Model Provider Headers",
  "models.providers.*.authHeader": "Model Provider Authorization Header",
  "models.providers.*.models": "Model Provider Model List",
  "models.bedrockDiscovery": "Bedrock Model Discovery",
  "models.bedrockDiscovery.enabled": "Bedrock Discovery Enabled",
  "models.bedrockDiscovery.region": "Bedrock Discovery Region",
  "models.bedrockDiscovery.providerFilter": "Bedrock Discovery Provider Filter",
  "models.bedrockDiscovery.refreshInterval": "Bedrock Discovery Refresh Interval (s)",
  "models.bedrockDiscovery.defaultContextWindow": "Bedrock Default Context Window",
  "models.bedrockDiscovery.defaultMaxTokens": "Bedrock Default Max Tokens",
  "auth.cooldowns.billingBackoffHours": "Billing Backoff (hours)",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing Backoff Overrides",
  "auth.cooldowns.billingMaxHours": "Billing Backoff Cap (hours)",
  "auth.cooldowns.failureWindowHours": "Failover Window (hours)",
  "agents.defaults.models": "Models",
  "agents.defaults.model.primary": "Primary Model",
  "agents.defaults.model.fallbacks": "Model Fallbacks",
  "agents.defaults.imageModel.primary": "Image Model",
  "agents.defaults.imageModel.fallbacks": "Image Model Fallbacks",
  "agents.defaults.imageGenerationModel.primary": "Image Generation Model",
  "agents.defaults.imageGenerationModel.fallbacks": "Image Generation Model Fallbacks",
  "agents.defaults.pdfModel.primary": "PDF Model",
  "agents.defaults.pdfModel.fallbacks": "PDF Model Fallbacks",
  "agents.defaults.pdfMaxBytesMb": "PDF Max Size (MB)",
  "agents.defaults.pdfMaxPages": "PDF Max Pages",
  "agents.defaults.imageMaxDimensionPx": "Image Max Dimension (px)",
  "agents.defaults.humanDelay.mode": "Human Delay Mode",
  "agents.defaults.humanDelay.minMs": "Human Delay Min (ms)",
  "agents.defaults.humanDelay.maxMs": "Human Delay Max (ms)",
  "agents.defaults.cliBackends": "CLI Backends",
  "agents.defaults.compaction": "Compaction",
  "agents.defaults.compaction.mode": "Compaction Mode",
  "agents.defaults.compaction.reserveTokens": "Compaction Reserve Tokens",
  "agents.defaults.compaction.keepRecentTokens": "Compaction Keep Recent Tokens",
  "agents.defaults.compaction.reserveTokensFloor": "Compaction Reserve Token Floor",
  "agents.defaults.compaction.maxHistoryShare": "Compaction Max History Share",
  "agents.defaults.compaction.identifierPolicy": "Compaction Identifier Policy",
  "agents.defaults.compaction.identifierInstructions": "Compaction Identifier Instructions",
  "agents.defaults.compaction.recentTurnsPreserve": "Compaction Preserve Recent Turns",
  "agents.defaults.compaction.qualityGuard": "Compaction Quality Guard",
  "agents.defaults.compaction.qualityGuard.enabled": "Compaction Quality Guard Enabled",
  "agents.defaults.compaction.qualityGuard.maxRetries": "Compaction Quality Guard Max Retries",
  "agents.defaults.compaction.postIndexSync": "Compaction Post-Index Sync",
  "agents.defaults.compaction.postCompactionSections": "Post-Compaction Context Sections",
  "agents.defaults.compaction.timeoutSeconds": "Compaction Timeout (Seconds)",
  "agents.defaults.compaction.model": "Compaction Model Override",
  "agents.defaults.compaction.truncateAfterCompaction": "Truncate After Compaction",
  "agents.defaults.compaction.memoryFlush": "Compaction Memory Flush",
  "agents.defaults.compaction.memoryFlush.enabled": "Compaction Memory Flush Enabled",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "Compaction Memory Flush Soft Threshold",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "Compaction Memory Flush Transcript Size Threshold",
  "agents.defaults.compaction.memoryFlush.prompt": "Compaction Memory Flush Prompt",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "Compaction Memory Flush System Prompt",
  "agents.defaults.embeddedPi": "Embedded Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "Embedded Pi Project Settings Policy",
  "agents.defaults.heartbeat.directPolicy": "Heartbeat Direct Policy",
  "agents.list.*.heartbeat.directPolicy": "Heartbeat Direct Policy",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "Heartbeat Suppress Tool Error Warnings",
  "agents.defaults.sandbox.browser.network": "Sandbox Browser Network",
  "agents.defaults.sandbox.browser.cdpSourceRange": "Sandbox Browser CDP Source Port Range",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Sandbox Docker Allow Container Namespace Join",
  commands: "Commands",
  "commands.native": "Native Commands",
  "commands.nativeSkills": "Native Skill Commands",
  "commands.text": "Text Commands",
  "commands.bash": "Allow Bash Chat Command",
  "commands.bashForegroundMs": "Bash Foreground Window (ms)",
  "commands.config": "Allow /config",
  "commands.mcp": "Allow /mcp",
  "commands.plugins": "Allow /plugins",
  "commands.debug": "Allow /debug",
  "commands.restart": "Allow Restart",
  "commands.useAccessGroups": "Use Access Groups",
  "commands.ownerAllowFrom": "Command Owners",
  "commands.ownerDisplay": "Owner ID Display",
  "commands.ownerDisplaySecret": "Owner ID Hash Secret", // pragma: allowlist secret
  "commands.allowFrom": "Command Elevated Access Rules",
  mcp: "MCP",
  "mcp.servers": "MCP Servers",
  ui: "UI",
  "ui.seamColor": "Accent Color",
  "ui.assistant": "Assistant Appearance",
  "ui.assistant.name": "Assistant Name",
  "ui.assistant.avatar": "Assistant Avatar",
  "browser.evaluateEnabled": "Browser Evaluate Enabled",
  "browser.snapshotDefaults": "Browser Snapshot Defaults",
  "browser.snapshotDefaults.mode": "Browser Snapshot Mode",
  "browser.ssrfPolicy": "Browser SSRF Policy",
  "browser.ssrfPolicy.allowPrivateNetwork": "Browser Allow Private Network",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "Browser Dangerously Allow Private Network",
  "browser.ssrfPolicy.allowedHostnames": "Browser Allowed Hostnames",
  "browser.ssrfPolicy.hostnameAllowlist": "Browser Hostname Allowlist",
  "browser.remoteCdpTimeoutMs": "Remote CDP Timeout (ms)",
  "browser.remoteCdpHandshakeTimeoutMs": "Remote CDP Handshake Timeout (ms)",
  session: "Session",
  "session.scope": "Session Scope",
  "session.dmScope": "DM Session Scope",
  "session.identityLinks": "Session Identity Links",
  "session.resetTriggers": "Session Reset Triggers",
  "session.idleMinutes": "Session Idle Minutes",
  "session.reset": "Session Reset Policy",
  "session.reset.mode": "Session Reset Mode",
  "session.reset.atHour": "Session Daily Reset Hour",
  "session.reset.idleMinutes": "Session Reset Idle Minutes",
  "session.resetByType": "Session Reset by Chat Type",
  "session.resetByType.direct": "Session Reset (Direct)",
  "session.resetByType.dm": "Session Reset (DM Deprecated Alias)",
  "session.resetByType.group": "Session Reset (Group)",
  "session.resetByType.thread": "Session Reset (Thread)",
  "session.resetByChannel": "Session Reset by Channel",
  "session.store": "Session Store Path",
  "session.typingIntervalSeconds": "Session Typing Interval (seconds)",
  "session.typingMode": "Session Typing Mode",
  "session.parentForkMaxTokens": "Session Parent Fork Max Tokens",
  "session.mainKey": "Session Main Key",
  "session.sendPolicy": "Session Send Policy",
  "session.sendPolicy.default": "Session Send Policy Default Action",
  "session.sendPolicy.rules": "Session Send Policy Rules",
  "session.sendPolicy.rules[].action": "Session Send Rule Action",
  "session.sendPolicy.rules[].match": "Session Send Rule Match",
  "session.sendPolicy.rules[].match.channel": "Session Send Rule Channel",
  "session.sendPolicy.rules[].match.chatType": "Session Send Rule Chat Type",
  "session.sendPolicy.rules[].match.keyPrefix": "Session Send Rule Key Prefix",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "Session Send Rule Raw Key Prefix",
  "session.agentToAgent": "Session Agent-to-Agent",
  "session.agentToAgent.maxPingPongTurns": "Agent-to-Agent Ping-Pong Turns",
  "session.threadBindings": "Session Thread Bindings",
  "session.threadBindings.enabled": "Thread Binding Enabled",
  "session.threadBindings.idleHours": "Thread Binding Idle Timeout (hours)",
  "session.threadBindings.maxAgeHours": "Thread Binding Max Age (hours)",
  "session.maintenance": "Session Maintenance",
  "session.maintenance.mode": "Session Maintenance Mode",
  "session.maintenance.pruneAfter": "Session Prune After",
  "session.maintenance.pruneDays": "Session Prune Days (Deprecated)",
  "session.maintenance.maxEntries": "Session Max Entries",
  "session.maintenance.rotateBytes": "Session Rotate Size",
  "session.maintenance.resetArchiveRetention": "Session Reset Archive Retention",
  "session.maintenance.maxDiskBytes": "Session Max Disk Budget",
  "session.maintenance.highWaterBytes": "Session Disk High-water Target",
  cron: "Cron",
  "cron.enabled": "Cron 已启用",
  "cron.store": "Cron 存储路径",
  "cron.maxConcurrentRuns": "Cron 最大并发运行数",
  "cron.retry": "Cron 重试策略",
  "cron.retry.maxAttempts": "Cron 重试最大尝试次数",
  "cron.retry.backoffMs": "Cron 重试退避(毫秒)",
  "cron.retry.retryOn": "Cron 重试错误类型",
  "cron.webhook": "Cron 传统 Webhook(已弃用)",
  "cron.webhookToken": "Cron Webhook Bearer 令牌",
  "cron.sessionRetention": "Cron 会话保留",
  "cron.runLog": "Cron 运行日志修剪",
  "cron.runLog.maxBytes": "Cron 运行日志最大字节数",
  "cron.runLog.keepLines": "Cron 运行日志保留行数",
  hooks: "Hooks",
  "hooks.enabled": "Hooks 已启用",
  "hooks.path": "Hooks 端点路径",
  "hooks.token": "Hooks 认证令牌",
  "hooks.defaultSessionKey": "Hooks 默认会话键",
  "hooks.allowRequestSessionKey": "Hooks 允许请求会话键",
  "hooks.allowedSessionKeyPrefixes": "Hooks 允许的会话键前缀",
  "hooks.allowedAgentIds": "Hooks 允许的智能体 ID",
  "hooks.maxBodyBytes": "Hooks 最大请求体字节数",
  "hooks.presets": "Hooks 预设",
  "hooks.transformsDir": "Hooks 转换目录",
  "hooks.mappings": "Hook 映射",
  "hooks.mappings[].id": "Hook 映射 ID",
  "hooks.mappings[].match": "Hook 映射匹配",
  "hooks.mappings[].match.path": "Hook 映射匹配路径",
  "hooks.mappings[].match.source": "Hook 映射匹配来源",
  "hooks.mappings[].action": "Hook 映射操作",
  "hooks.mappings[].wakeMode": "Hook 映射唤醒模式",
  "hooks.mappings[].name": "Hook 映射名称",
  "hooks.mappings[].agentId": "Hook 映射智能体 ID",
  "hooks.mappings[].sessionKey": "Hook 映射会话键",
  "hooks.mappings[].messageTemplate": "Hook 映射消息模板",
  "hooks.mappings[].textTemplate": "Hook 映射文本模板",
  "hooks.mappings[].deliver": "Hook 映射交付回复",
  "hooks.mappings[].allowUnsafeExternalContent": "Hook 映射允许不安全外部内容",
  "hooks.mappings[].channel": "Hook 映射交付频道",
  "hooks.mappings[].to": "Hook 映射交付目的地",
  "hooks.mappings[].model": "Hook 映射模型覆盖",
  "hooks.mappings[].thinking": "Hook 映射思考覆盖",
  "hooks.mappings[].timeoutSeconds": "Hook 映射超时(秒)",
  "hooks.mappings[].transform": "Hook 映射转换",
  "hooks.mappings[].transform.module": "Hook 转换模块",
  "hooks.mappings[].transform.export": "Hook 转换导出",
  "hooks.gmail": "Gmail Hook",
  "hooks.gmail.account": "Gmail Hook 账户",
  "hooks.gmail.label": "Gmail Hook 标签",
  "hooks.gmail.topic": "Gmail Hook 发布/订阅主题",
  "hooks.gmail.subscription": "Gmail Hook 订阅",
  "hooks.gmail.pushToken": "Gmail Hook 推送令牌",
  "hooks.gmail.hookUrl": "Gmail Hook 回调 URL",
  "hooks.gmail.includeBody": "Gmail Hook 包含正文",
  "hooks.gmail.maxBytes": "Gmail Hook 最大正文字节数",
  "hooks.gmail.renewEveryMinutes": "Gmail Hook 续订间隔(分钟)",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail Hook 允许不安全外部内容",
  "hooks.gmail.serve": "Gmail Hook 本地服务器",
  "hooks.gmail.serve.bind": "Gmail Hook 服务器绑定地址",
  "hooks.gmail.serve.port": "Gmail Hook 服务器端口",
  "hooks.gmail.serve.path": "Gmail Hook 服务器路径",
  "hooks.gmail.tailscale": "Gmail Hook Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail Hook Tailscale Mode",
  "hooks.gmail.tailscale.path": "Gmail Hook Tailscale Path",
  "hooks.gmail.tailscale.target": "Gmail Hook Tailscale Target",
  "hooks.gmail.model": "Gmail Hook Model Override",
  "hooks.gmail.thinking": "Gmail Hook Thinking Override",
  "hooks.internal": "Internal Hooks",
  "hooks.internal.enabled": "Internal Hooks Enabled",
  "hooks.internal.handlers": "Internal Hook Handlers",
  "hooks.internal.handlers[].event": "Internal Hook Event",
  "hooks.internal.handlers[].module": "Internal Hook Module",
  "hooks.internal.handlers[].export": "Internal Hook Export",
  "hooks.internal.entries": "Internal Hook Entries",
  "hooks.internal.load": "Internal Hook Loader",
  "hooks.internal.load.extraDirs": "Internal Hook Extra Directories",
  "hooks.internal.installs": "Internal Hook Install Records",
  web: "Web Channel",
  "web.enabled": "Web Channel Enabled",
  "web.heartbeatSeconds": "Web Channel Heartbeat Interval (sec)",
  "web.reconnect": "Web Channel Reconnect Policy",
  "web.reconnect.initialMs": "Web Reconnect Initial Delay (ms)",
  "web.reconnect.maxMs": "Web Reconnect Max Delay (ms)",
  "web.reconnect.factor": "Web Reconnect Backoff Factor",
  "web.reconnect.jitter": "Web Reconnect Jitter",
  "web.reconnect.maxAttempts": "Web Reconnect Max Attempts",
  discovery: "Discovery",
  "discovery.wideArea": "Wide-area Discovery",
  "discovery.wideArea.enabled": "Wide-area Discovery Enabled",
  "discovery.wideArea.domain": "Wide-area Discovery Domain",
  "discovery.mdns": "mDNS Discovery",
  canvasHost: "Canvas Host",
  "canvasHost.enabled": "Canvas Host Enabled",
  "canvasHost.root": "Canvas Host Root Directory",
  "canvasHost.port": "Canvas Host Port",
  "canvasHost.liveReload": "Canvas Host Live Reload",
  talk: "Talk",
  "talk.voiceId": "Talk 语音 ID",
  "talk.voiceAliases": "Talk 语音别名",
  "talk.modelId": "Talk 模型 ID",
  "talk.outputFormat": "Talk 输出格式",
  "talk.interruptOnSpeech": "Talk 在语音上中断",
  "talk.silenceTimeoutMs": "Talk 沉默超时(毫秒)",
  messages: "消息",
  "messages.messagePrefix": "入站消息前缀",
  "messages.responsePrefix": "出站响应前缀",
  "messages.groupChat": "群组聊天规则",
  "messages.groupChat.mentionPatterns": "群组提及模式",
  "messages.groupChat.historyLimit": "群组历史限制",
  "messages.queue": "入站队列",
  "messages.queue.mode": "队列模式",
  "messages.queue.byChannel": "按频道排队模式",
  "messages.queue.debounceMs": "队列防抖(毫秒)",
  "messages.queue.debounceMsByChannel": "按频道排队防抖(毫秒)",
  "messages.queue.cap": "队列容量",
  "messages.queue.drop": "队列丢弃策略",
  "messages.inbound": "入站防抖",
  "messages.suppressToolErrors": "抑制工具错误警告",
  "messages.ackReaction": "确认反应表情符号",
  "messages.ackReactionScope": "确认反应范围",
  "messages.removeAckAfterReply": "回复后移除确认反应",
  "messages.statusReactions": "状态反应",
  "messages.statusReactions.enabled": "启用状态反应",
  "messages.statusReactions.emojis": "状态反应表情符号",
  "messages.statusReactions.timing": "状态反应时间",
  "messages.inbound.debounceMs": "入站消息防抖(毫秒)",
  "messages.inbound.byChannel": "按频道入站防抖(毫秒)",
  "messages.tts": "消息文本转语音",
  "talk.provider": "Talk 活跃提供商",
  "talk.providers": "Talk 提供商设置",
  "talk.providers.*.voiceId": "Talk 提供商语音 ID",
  "talk.providers.*.voiceAliases": "Talk 提供商语音别名",
  "talk.providers.*.modelId": "Talk 提供商模型 ID",
  "talk.providers.*.outputFormat": "Talk 提供商输出格式",
  "talk.providers.*.apiKey": "Talk 提供商 API 密钥",
  "talk.apiKey": "Talk API 密钥",
  channels: "频道",
  "channels.defaults": "频道默认值",
  "channels.defaults.groupPolicy": "默认群组策略",
  "channels.defaults.heartbeat": "默认心跳可见性",
  "channels.defaults.heartbeat.showOk": "心跳显示正常",
  "channels.defaults.heartbeat.showAlerts": "心跳显示警报",
  "channels.defaults.heartbeat.useIndicator": "心跳使用指示器",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram 自定义命令",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  "channels.modelByChannel": "频道模型覆盖",
  ...IRC_FIELD_LABELS,
  "channels.telegram.botToken": "Telegram 机器人令牌",
  "channels.telegram.dmPolicy": "Telegram 直接消息策略",
  "channels.telegram.configWrites": "Telegram 配置写入",
  "channels.telegram.commands.native": "Telegram 原生命令",
  "channels.telegram.commands.nativeSkills": "Telegram 原生技能命令",
  "channels.telegram.streaming": "Telegram 流模式",
  "channels.telegram.retry.attempts": "Telegram 重试尝试次数",
  "channels.telegram.retry.minDelayMs": "Telegram 重试最小延迟(毫秒)",
  "channels.telegram.retry.maxDelayMs": "Telegram 重试最大延迟(毫秒)",
  "channels.telegram.retry.jitter": "Telegram 重试抖动",
  "channels.telegram.network.autoSelectFamily": "Telegram autoSelectFamily",
  "channels.telegram.timeoutSeconds": "Telegram API Timeout (seconds)",
  "channels.telegram.silentErrorReplies": "Telegram Silent Error Replies",
  "channels.telegram.apiRoot": "Telegram API Root URL",
  "channels.telegram.autoTopicLabel": "Telegram Auto Topic Label",
  "channels.telegram.autoTopicLabel.enabled": "Telegram Auto Topic Label Enabled",
  "channels.telegram.autoTopicLabel.prompt": "Telegram Auto Topic Label Prompt",
  "channels.telegram.capabilities.inlineButtons": "Telegram Inline Buttons",
  "channels.telegram.execApprovals": "Telegram Exec Approvals",
  "channels.telegram.execApprovals.enabled": "Telegram Exec Approvals Enabled",
  "channels.telegram.execApprovals.approvers": "Telegram Exec Approval Approvers",
  "channels.telegram.execApprovals.agentFilter": "Telegram Exec Approval Agent Filter",
  "channels.telegram.execApprovals.sessionFilter": "Telegram Exec Approval Session Filter",
  "channels.telegram.execApprovals.target": "Telegram Exec Approval Target",
  "channels.telegram.threadBindings.enabled": "Telegram Thread Binding Enabled",
  "channels.telegram.threadBindings.idleHours": "Telegram Thread Binding Idle Timeout (hours)",
  "channels.telegram.threadBindings.maxAgeHours": "Telegram Thread Binding Max Age (hours)",
  "channels.telegram.threadBindings.spawnSubagentSessions": "Telegram Thread-Bound Subagent Spawn",
  "channels.telegram.threadBindings.spawnAcpSessions": "Telegram Thread-Bound ACP Spawn",
  "channels.whatsapp.dmPolicy": "WhatsApp DM Policy",
  "channels.whatsapp.selfChatMode": "WhatsApp Self-Phone Mode",
  "channels.whatsapp.debounceMs": "WhatsApp Message Debounce (ms)",
  "channels.whatsapp.configWrites": "WhatsApp Config Writes",
  "channels.signal.dmPolicy": "Signal DM Policy",
  "channels.signal.configWrites": "Signal Config Writes",
  "channels.imessage.dmPolicy": "iMessage DM Policy",
  "channels.imessage.configWrites": "iMessage Config Writes",
  "channels.bluebubbles.dmPolicy": "BlueBubbles DM Policy",
  "channels.msteams.configWrites": "MS Teams Config Writes",
  "channels.irc.configWrites": "IRC Config Writes",
  "channels.discord.dmPolicy": "Discord DM Policy",
  "channels.discord.dm.policy": "Discord DM Policy",
  "channels.discord.configWrites": "Discord Config Writes",
  "channels.discord.proxy": "Discord Proxy URL",
  "channels.discord.commands.native": "Discord Native Commands",
  "channels.discord.commands.nativeSkills": "Discord Native Skill Commands",
  "channels.discord.streaming": "Discord Streaming Mode",
  "channels.discord.streamMode": "Discord Stream Mode (Legacy)",
  "channels.discord.draftChunk.minChars": "Discord Draft Chunk Min Chars",
  "channels.discord.draftChunk.maxChars": "Discord Draft Chunk Max Chars",
  "channels.discord.draftChunk.breakPreference": "Discord Draft Chunk Break Preference",
  "channels.discord.retry.attempts": "Discord Retry Attempts",
  "channels.discord.retry.minDelayMs": "Discord Retry Min Delay (ms)",
  "channels.discord.retry.maxDelayMs": "Discord Retry Max Delay (ms)",
  "channels.discord.retry.jitter": "Discord Retry Jitter",
  "channels.discord.maxLinesPerMessage": "Discord Max Lines Per Message",
  "channels.discord.inboundWorker.runTimeoutMs": "Discord Inbound Worker Timeout (ms)",
  "channels.discord.eventQueue.listenerTimeout": "Discord EventQueue Listener Timeout (ms)",
  "channels.discord.eventQueue.maxQueueSize": "Discord EventQueue Max Queue Size",
  "channels.discord.eventQueue.maxConcurrency": "Discord EventQueue Max Concurrency",
  "channels.discord.threadBindings.enabled": "Discord Thread Binding Enabled",
  "channels.discord.threadBindings.idleHours": "Discord Thread Binding Idle Timeout (hours)",
  "channels.discord.threadBindings.maxAgeHours": "Discord Thread Binding Max Age (hours)",
  "channels.discord.threadBindings.spawnSubagentSessions": "Discord Thread-Bound Subagent Spawn",
  "channels.discord.threadBindings.spawnAcpSessions": "Discord Thread-Bound ACP Spawn",
  "channels.discord.ui.components.accentColor": "Discord Component Accent Color",
  "channels.discord.intents.presence": "Discord Presence Intent",
  "channels.discord.intents.guildMembers": "Discord 工会成员 Intent",
  "channels.discord.voice.enabled": "Discord 语音已启用",
  "channels.discord.voice.autoJoin": "Discord 语音自动加入",
  "channels.discord.voice.daveEncryption": "Discord 语音 DAVE 加密",
  "channels.discord.voice.decryptionFailureTolerance": "Discord 语音解密失败容限",
  "channels.discord.voice.tts": "Discord 语音文本转语音",
  "channels.discord.pluralkit.enabled": "Discord PluralKit 已启用",
  "channels.discord.pluralkit.token": "Discord PluralKit 令牌",
  "channels.discord.activity": "Discord Presence Activity",
  "channels.discord.status": "Discord Presence 状态",
  "channels.discord.autoPresence.enabled": "Discord 自动 Presence 已启用",
  "channels.discord.autoPresence.intervalMs": "Discord 自动 Presence 检查间隔(毫秒)",
  "channels.discord.autoPresence.minUpdateIntervalMs": "Discord 自动 Presence 最小更新间隔(毫秒)",
  "channels.discord.autoPresence.healthyText": "Discord 自动 Presence 健康文本",
  "channels.discord.autoPresence.degradedText": "Discord 自动 Presence 降级文本",
  "channels.discord.autoPresence.exhaustedText": "Discord 自动 Presence 耗尽文本",
  "channels.discord.activityType": "Discord Presence Activity 类型",
  "channels.discord.activityUrl": "Discord Presence Activity URL",
  "channels.slack.dm.policy": "Slack DM Policy",
  "channels.slack.dmPolicy": "Slack DM Policy",
  "channels.slack.configWrites": "Slack Config Writes",
  "channels.slack.commands.native": "Slack Native Commands",
  "channels.slack.commands.nativeSkills": "Slack Native Skill Commands",
  "channels.slack.allowBots": "Slack Allow Bot Messages",
  "channels.discord.allowBots": "Discord Allow Bot Messages",
  "channels.matrix.allowBots": "Matrix Allow Bot Messages",
  "channels.discord.token": "Discord Bot Token",
  "channels.slack.botToken": "Slack Bot Token",
  "channels.slack.appToken": "Slack App Token",
  "channels.slack.userToken": "Slack User Token",
  "channels.slack.userTokenReadOnly": "Slack User Token Read Only",
  "channels.slack.capabilities.interactiveReplies": "Slack Interactive Replies",
  "channels.slack.streaming": "Slack Streaming Mode",
  "channels.slack.nativeStreaming": "Slack Native Streaming",
  "channels.slack.streamMode": "Slack Stream Mode (Legacy)",
  "channels.slack.thread.historyScope": "Slack Thread History Scope",
  "channels.slack.thread.inheritParent": "Slack Thread Parent Inheritance",
  "channels.slack.thread.initialHistoryLimit": "Slack Thread Initial History Limit",
  "channels.mattermost.botToken": "Mattermost Bot Token",
  "channels.mattermost.baseUrl": "Mattermost Base URL",
  "channels.mattermost.configWrites": "Mattermost Config Writes",
  "channels.mattermost.chatmode": "Mattermost Chat Mode",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar Prefixes",
  "channels.mattermost.requireMention": "Mattermost Require Mention",
  "channels.signal.account": "Signal Account",
  "channels.imessage.cliPath": "iMessage CLI Path",
  "agents.list[].skills": "Agent Skill Filter",
  "agents.list[].identity.avatar": "Agent Avatar",
  "agents.list[].heartbeat.suppressToolErrorWarnings":
    "Agent Heartbeat Suppress Tool Error Warnings",
  "agents.list[].sandbox.browser.network": "Agent Sandbox Browser Network",
  "agents.list[].sandbox.browser.cdpSourceRange": "Agent Sandbox Browser CDP Source Port Range",
  "agents.list[].sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Agent Sandbox Docker Allow Container Namespace Join",
  "discovery.mdns.mode": "mDNS Discovery Mode",
  plugins: "Plugins",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load": "Plugin Loader",
  "plugins.load.paths": "Plugin Load Paths",
  "plugins.slots": "Plugin Slots",
  "plugins.slots.memory": "Memory Plugin",
  "plugins.slots.contextEngine": "Context Engine Plugin",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.hooks": "Plugin Hook Policy",
  "plugins.entries.*.hooks.allowPromptInjection": "Allow Prompt Injection Hooks",
  "plugins.entries.*.subagent": "Plugin Subagent Policy",
  "plugins.entries.*.subagent.allowModelOverride": "Allow Plugin Subagent Model Override",
  "plugins.entries.*.subagent.allowedModels": "Plugin Subagent Allowed Models",
  "plugins.entries.*.apiKey": "Plugin API Key", // pragma: allowlist secret
  "plugins.entries.*.env": "Plugin Environment Variables",
  "plugins.entries.*.config": "Plugin Config",
  "plugins.installs": "Plugin Install Records",
  "plugins.installs.*.source": "Plugin Install Source",
  "plugins.installs.*.spec": "Plugin Install Spec",
  "plugins.installs.*.sourcePath": "Plugin Install Source Path",
  "plugins.installs.*.installPath": "Plugin Install Path",
  "plugins.installs.*.version": "Plugin Install Version",
  "plugins.installs.*.resolvedName": "Plugin Resolved Package Name",
  "plugins.installs.*.resolvedVersion": "Plugin Resolved Package Version",
  "plugins.installs.*.resolvedSpec": "Plugin Resolved Package Spec",
  "plugins.installs.*.integrity": "Plugin Resolved Integrity",
  "plugins.installs.*.shasum": "Plugin Resolved Shasum",
  "plugins.installs.*.resolvedAt": "Plugin Resolution Time",
  "plugins.installs.*.installedAt": "Plugin Install Time",
  "plugins.installs.*.marketplaceName": "Plugin Marketplace Name",
  "plugins.installs.*.marketplaceSource": "Plugin Marketplace Source",
  "plugins.installs.*.marketplacePlugin": "Plugin Marketplace Plugin",
};
